from __future__ import annotations

import json
import re
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = ROOT / "scripts" / "schema_convert"

SCHEMAS = {
    "h2": ROOT / "src/main/resources/db/h2/schema.sql",
    "mysql": ROOT / "src/main/resources/db/mysql/schema.sql",
    "postgres": ROOT / "src/main/resources/db/postgres/schema.sql",
}


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def collect_schema_facts(sql: str) -> dict:
    tables = re.findall(r"CREATE\s+TABLE(?:\s+IF\s+NOT\s+EXISTS)?\s+([a-zA-Z_][a-zA-Z0-9_]*)", sql, re.I)
    indexes = re.findall(r"CREATE\s+INDEX(?:\s+[a-zA-Z_][a-zA-Z0-9_]*)?\s+ON\s+([a-zA-Z_][a-zA-Z0-9_]*)|CREATE\s+INDEX\s+([a-zA-Z_][a-zA-Z0-9_]*)", sql, re.I)
    fk_refs = re.findall(r"REFERENCES\s+([a-zA-Z_][a-zA-Z0-9_]*)", sql, re.I)
    identity = re.findall(r"IDENTITY|AUTO_INCREMENT", sql, re.I)
    unique = re.findall(r"\bUNIQUE\b", sql, re.I)

    flattened_indexes = [left or right for left, right in indexes]

    return {
        "tables": sorted(set(tables)),
        "table_count": len(set(tables)),
        "index_count": len(flattened_indexes),
        "foreign_key_count": len(fk_refs),
        "identity_count": len(identity),
        "unique_count": len(unique),
    }


def main() -> None:
    sql_by_profile = {name: read_text(path) for name, path in SCHEMAS.items()}
    facts = {name: collect_schema_facts(sql) for name, sql in sql_by_profile.items()}

    findings = [
        {
            "id": "SC-001",
            "severity": "info",
            "source": "postgres",
            "finding": "PostgreSQL schema is already available and compatible with Azure Database for PostgreSQL Flexible Server.",
            "remediation": "Use native PostgreSQL migration with pg_dump and pg_restore; no SSMA conversion is required.",
        },
        {
            "id": "SC-002",
            "severity": "medium",
            "source": "h2",
            "finding": "H2 uses VARCHAR_IGNORECASE for owners.last_name.",
            "remediation": "Target PostgreSQL uses TEXT. If case-insensitive search must be preserved at the database layer, add citext or a lower(last_name) functional index.",
        },
        {
            "id": "SC-003",
            "severity": "low",
            "source": "h2",
            "finding": "H2 drop-table syntax and embedded identity behavior are not target deployment patterns.",
            "remediation": "Use PostgreSQL DDL with CREATE TABLE IF NOT EXISTS and GENERATED BY DEFAULT AS IDENTITY.",
        },
        {
            "id": "SC-004",
            "severity": "medium",
            "source": "mysql",
            "finding": "MySQL schema uses AUTO_INCREMENT, UNSIGNED integer display widths and engine=InnoDB.",
            "remediation": "PostgreSQL target maps identity columns to GENERATED BY DEFAULT AS IDENTITY, removes UNSIGNED/display widths and omits storage-engine syntax.",
        },
        {
            "id": "SC-005",
            "severity": "info",
            "source": "all",
            "finding": "PetClinic schema has seven application tables: vets, specialties, vet_specialties, types, owners, pets and visits.",
            "remediation": "Validate row counts, checksums, FK relationships and identity sequence values after restore.",
        },
    ]

    report = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "target": "Azure Database for PostgreSQL Flexible Server",
        "selected_source_profile": "postgres",
        "conversion_mode": "native PostgreSQL compatible",
        "facts": facts,
        "findings": findings,
    }

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUTPUT_DIR / "conversion_report.json").write_text(json.dumps(report, indent=2), encoding="utf-8")

    lines = [
        "# Schema Conversion Report",
        "",
        f"Generated at: `{report['generated_at']}`",
        "",
        "| Item | Value |",
        "|---|---|",
        "| Selected source profile | PostgreSQL |",
        "| Azure target | Azure Database for PostgreSQL Flexible Server |",
        "| Conversion mode | Native PostgreSQL-compatible migration |",
        "| SSMA required | No |",
        "",
        "## Schema Object Summary",
        "",
        "| Profile | Tables | Indexes | FK References | Identity Columns | Unique Constraints |",
        "|---|---:|---:|---:|---:|---:|",
    ]

    for profile, fact in facts.items():
        lines.append(
            f"| {profile} | {fact['table_count']} | {fact['index_count']} | {fact['foreign_key_count']} | "
            f"{fact['identity_count']} | {fact['unique_count']} |"
        )

    lines.extend([
        "",
        "## Findings And Remediation",
        "",
        "| ID | Severity | Source | Finding | Remediation |",
        "|---|---|---|---|---|",
    ])

    for finding in findings:
        lines.append(
            f"| {finding['id']} | {finding['severity']} | {finding['source']} | "
            f"{finding['finding']} | {finding['remediation']} |"
        )

    lines.extend([
        "",
        "## Post-Migration Validation Required",
        "",
        "- Row counts per table must match.",
        "- Checksums/hashes for critical tables must match.",
        "- Foreign-key spot checks must pass for pets, visits and vet specialties.",
        "- Identity sequence next values must be greater than the max table ID.",
        "- Application smoke queries must pass after connection string cutover.",
    ])

    (OUTPUT_DIR / "conversion_report.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUTPUT_DIR / 'conversion_report.md'}")
    print(f"Wrote {OUTPUT_DIR / 'conversion_report.json'}")


if __name__ == "__main__":
    main()
