type: Microsoft.App/containerApps
name: petclinic-container-app
properties:
  configuration:
    secrets:
      - name: petclinic-postgres-jdbc-url
        keyVaultUrl: "https://<key-vault-name>.vault.azure.net/secrets/petclinic-postgres-jdbc-url"
        identity: "<user-assigned-managed-identity-resource-id>"
      - name: petclinic-postgres-username
        keyVaultUrl: "https://<key-vault-name>.vault.azure.net/secrets/petclinic-postgres-username"
        identity: "<user-assigned-managed-identity-resource-id>"
      - name: petclinic-postgres-password
        keyVaultUrl: "https://<key-vault-name>.vault.azure.net/secrets/petclinic-postgres-password"
        identity: "<user-assigned-managed-identity-resource-id>"
  template:
    containers:
      - name: spring-petclinic
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: postgres,azure
          - name: PETCLINIC_CONFIG_SOURCE
            value: azure-app-configuration
          - name: PETCLINIC_EXTERNALIZED_CONFIG
            value: "true"
          - name: PETCLINIC_FEATURE_EXPERIMENTAL_UI
            value: "false"
          - name: POSTGRES_URL
            secretRef: petclinic-postgres-jdbc-url
          - name: POSTGRES_USER
            secretRef: petclinic-postgres-username
          - name: POSTGRES_PASS
            secretRef: petclinic-postgres-password
          - name: SPRING_DATASOURCE_HIKARI_DATA_SOURCE_PROPERTIES_SSLMODE
            value: require
          - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
            value: health,info
